# Current issues:
- [A stack question](http://stackoverflow.com/questions/31967010/getting-authors-articles-from-scopus-using-scopus-api-authentication-error)
- *scopus_exercise.py* Traceback:
``
<service-error>
	<status>
		<statusCode>AUTHENTICATION_ERROR</statusCode>
		<statusText>Client IP Address: 157.253.146.121 does not resolve to an account</statusText>
	</status>
</service-error>
``
